version: '3.8'
services:
  nexus:
    image: sonatype/nexus3
    container_name: nxs
    volumes:
      - ./outputs/nexus-data:/nexus-data
    ports:
      - 0.0.0.0:8081:8081
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/service/rest/v1/status/writable"]
      interval: 5s
      timeout: 4s
      retries: 30
  mdb:
    image: mongo:6-jammy
    container_name: mdb
    command: --quiet --logpath /dev/null
    ports:
      - 0.0.0.0:27017:27017
    volumes:
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 2s
      timeout: 2s
      retries: 5
  pdb:
    image: postgres:14.1-alpine
    container_name: pdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 0.0.0.0:5432:5432
    volumes: 
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 5