# Compile our java files in this container
FROM ubuntu:22.04 AS builder

# get and set graalvm-jdk-21
RUN apt-get update && apt-get install wget -y
RUN wget https://download.oracle.com/graalvm/21/archive/graalvm-jdk-21_linux-x64_bin.tar.gz && tar -xf graalvm-jdk-21_linux-x64_bin.tar.gz
RUN mv graalvm*/ graalvm-jdk-21/
ENV JAVA_HOME=./graalvm-jdk-21
RUN export JAVA_HOME

COPY . .

# compile app
# sharing a network repository seems like a good idea if you already have one, but the first load takes 180s~ and later 18s~, while not using it takes 27s~ (for java apps)
RUN mkdir ~/.m2 && echo "<settings> <mirrors> <mirror> <id>nexus</id> <mirrorOf>*</mirrorOf> <url>http://host.docker.internal:8081/repository/maven-public/</url> </mirror> </mirrors> </settings>" > ~/.m2/settings.xml
RUN apt-get update && apt-get install gcc zlib1g-dev -y
RUN sh mvnw -Pnative clean native:compile -pl ${APP_NAME}

# the final container
FROM frolvlad/alpine-glibc:alpine-3.18
RUN apk --no-cache add curl
COPY --from=builder ${APP_NAME}/target/${APP_NAME} /usr/local/bin/${APP_NAME}
ENTRYPOINT ["${APP_NAME}"]