version: '3.8'
services:
  app:
    image: ${appntag}
    container_name: app
    networks:
      - ext-stress-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/quote/11"]
      interval: 5s
      timeout: 4s
      retries: 6
    environment:
      - SPRING_APPLICATION_NAME=${spring_app_name}
      - SPRING_DATA_MONGODB_URI=mongodb://mdb:27017/test
      - SPRING_DATA_REDIS_URL=redis://red:6379
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pdb:5432/postgres
      - SPRING_R2DBC_URL=r2dbc:postgresql://pdb:5432/postgres
    deploy:
      resources:
        limits:
          cpus: '${cpus}'
          memory: 1G
  jmt:
    image: justb4/jmeter
    container_name: jmt
    networks:
      - ext-stress-network
    depends_on:
      app:
        condition: service_healthy
    volumes: 
      - ../:/mapped_dir
    command: -JDELAY=${delay} -JRAMP_UP=${ramp_up} -JDURATION=${duration} -JTHREADS=${clients} -Jjmeter.reportgenerator.overall_granularity=${report_granurality} -n -t /mapped_dir/JMeter_test_plan.jmx -l /mapped_dir/${workspace}/JMeter_test_plan.jtl -j /mapped_dir/${workspace}/JMeter_test_plan.log -e -o /mapped_dir/${workspace}/report

networks:
  ext-stress-network:
    name: stress-network
    external: true