SET quote_1 "{\"id\":1,\"quote\":\"There are only two kinds of languages: the ones people complain about and the ones nobody uses.\",\"author\":\"Bjarne Stroustrup\"}"
SET quote_2 "{\"id\":2,\"quote\":\"Any fool can write code that a computer can understand. Good programmers write code that humans can understand.\",\"author\":\"Martin Fowler\"}"
SET quote_3 "{\"id\":3,\"quote\":\"First, solve the problem. Then, write the code.\",\"author\":\"John Johnson\"}"
SET quote_4 "{\"id\":4,\"quote\":\"Java is to JavaScript what car is to Carpet.\",\"author\":\"Chris Heilmann\"}"
SET quote_5 "{\"id\":5,\"quote\":\"Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.\",\"author\":\"John Woods\"}"
SET quote_6 "{\"id\":6,\"quote\":\"I'm not a great programmer; I'm just a good programmer with great habits.\",\"author\":\"Kent Beck\"}"
SET quote_7 "{\"id\":7,\"quote\":\"Truth can only be found in one place: the code.\",\"author\":\"Robert C. Martin\"}"
SET quote_8 "{\"id\":8,\"quote\":\"If you have to spend effort looking at a fragment of code and figuring out what it's doing, then you should extract it into a function and name the function after the 'what'.\",\"author\":\"Martin Fowler\"}"
SET quote_9 "{\"id\":9,\"quote\":\"The real problem is that programmers have spent far too much time worrying about efficiency in the wrong places and at the wrong times; premature optimization is the root of all evil new Quote(or at least most of it) in programming.\",\"author\":\"Donald Knuth\"}"
SET quote_10 "{\"id\":10,\"quote\":\"SQL, Lisp, and Haskell are the only programming languages that I’ve seen where one spends more time thinking than typing.\",\"author\":\"Philip Greenspun\"}"
SET quote_11 "{\"id\":11,\"quote\":\"Deleted code is debugged code.\",\"author\":\"Jeff Sickel\"}"
SET quote_12 "{\"id\":12,\"quote\":\"There are two ways of constructing a software design: One way is to make it so simple that there are obviously no deficiencies and the other way is to make it so complicated that there are no obvious deficiencies.\",\"author\":\"C.A.R. Hoare\"}"
SET quote_13 "{\"id\":13,\"quote\":\"Simplicity is prerequisite for reliability.\",\"author\":\"Edsger W. Dijkstra\"}"
SET quote_14 "{\"id\":14,\"quote\":\"There are only two hard things in Computer Science: cache invalidation and naming things.\",\"author\":\"Phil Karlton\"}"
SET quote_15 "{\"id\":15,\"quote\":\"Measuring programming progress by lines of code is like measuring aircraft building progress by weight.\",\"author\":\"Bill Gates\"}"
SET quote_16 "{\"id\":16,\"quote\":\"Controlling complexity is the essence of computer programming.\",\"author\":\"Brian Kernighan\"}"
SET quote_17 "{\"id\":17,\"quote\":\"The only way to learn a new programming language is by writing programs in it.\",\"author\":\"Dennis Ritchie\"}"